# This is a basic workflow to help you get started with Actions

name: Create Pull Request on Main

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "dev" branch
  push:
    branches: [ "dev" ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install Dependencies
        run: npm i
      
      - name: Run tests
        run: npm run test
      
      - name: Create Pull Request
        if: ${{ success() }} # only run this if previous ci steps pass
        uses: actions/github-script@v6 # Official Github action to run scripts in workflow file
        with:
          script: | # create pull request using github api
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: 'Main pull request',
              owner,
              repo,
              head: '${{ github.ref_name }}',
              base: 'main',
              body: [
                'This PR is auto-generated by',
                '[actions/github-script](https://github.com/actions/github-script).'
              ].join('\n')
            });
          
